version: 2

sources:
    - name: staging
      database: mlops-zoom-camp-2023
      schema: taxi_tripdata

      tables:
          - name: fhv_tripdata
          - name: yellow_tripdata
          - name: green_tripdata